/* GENERATED by tools/build-shop-data.py -- do not edit by hand.
   Re-run after any price or product change in Square. */
window.PRINT_SHOP = {
 "formats": [
  {
   "key": "poster",
   "label": "Fine Art Poster",
   "blurb": "Museum-quality matte paper, 189 g/m² and 10.3 mil thick, at 94% opacity. No glare, deep blacks, ready to frame however you like.",
   "sizes": [
    {
     "size": "6x8",
     "price": 25
    },
    {
     "size": "12x16",
     "price": 35
    },
    {
     "size": "18x24",
     "price": 40
    }
   ]
  },
  {
   "key": "framed-poster",
   "label": "Framed Poster",
   "blurb": "The same matte print, set in a 0.75″ ayous wood frame from renewable forests, behind an acrylite front protector. Hanging hardware included.",
   "sizes": [
    {
     "size": "8x10",
     "price": 55
    },
    {
     "size": "12x16",
     "price": 80
    },
    {
     "size": "18x24",
     "price": 105
    }
   ]
  },
  {
   "key": "canvas",
   "label": "Gallery Canvas",
   "blurb": "1.25″ thick poly-cotton canvas, hand-stretched over solid wood stretcher bars with mounting brackets fitted. Fade-resistant, and it arrives ready to hang.",
   "sizes": [
    {
     "size": "9x12",
     "price": 45
    },
    {
     "size": "12x16",
     "price": 60
    },
    {
     "size": "18x24",
     "price": 80
    }
   ]
  },
  {
   "key": "framed-canvas",
   "label": "Framed Canvas",
   "blurb": "Canvas set in a 1.25″ pine frame with an open back, which gives the piece a floating effect. Rubber pads and wall mount fitted.",
   "sizes": [
    {
     "size": "9x12",
     "price": 75
    },
    {
     "size": "12x16",
     "price": 115
    },
    {
     "size": "18x24",
     "price": 155
    }
   ]
  },
  {
   "key": "metal",
   "label": "Metal Print",
   "blurb": "Aluminium on an MDF wood frame, hanging half an inch off the wall. Scratch- and fade-resistant, and luminescent against the wall.",
   "sizes": [
    {
     "size": "8x10",
     "price": 90
    },
    {
     "size": "11x14",
     "price": 120
    },
    {
     "size": "16x20",
     "price": 170
    }
   ]
  }
 ],
 "art": {
  "foundry-drake": {
   "title": "Foundry Drake",
   "kind": "Creature Design · Landscape",
   "thumb": "Images/thumbs/Foundry_Drake.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/foundry-drake-canvas/ITTAYN5N5Q64JTKRBCQNJEOW",
    "framed-canvas": "https://miles2walk.square.site/product/foundry-drake-framed-canvas/ENWPCMDFICDQ23S5N7Z5JS7T",
    "framed-poster": "https://miles2walk.square.site/product/foundry-drake-framed-poster/TRRKAQNUWBX47QHQNP2IFKXT",
    "metal": "https://miles2walk.square.site/product/foundry-drake-metal/WRUKIOZJX2AZWQIR7NKQZ5PU",
    "poster": "https://miles2walk.square.site/product/foundry-drake-poster/XS6SLST27DOXOKPSSWLDD4JS"
   },
   "mockups": {
    "poster": "Images/mockups/foundry-drake-poster.webp",
    "framed-poster": "Images/mockups/foundry-drake-framed-poster.webp",
    "canvas": "Images/mockups/foundry-drake-canvas.webp",
    "framed-canvas": "Images/mockups/foundry-drake-framed-canvas.webp",
    "metal": "Images/mockups/foundry-drake-metal.webp"
   }
  },
  "kaiju-picnic": {
   "title": "Kaiju Picnic",
   "kind": "Environment · Portrait",
   "thumb": "Images/thumbs/Kaiju_Picnic.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/kaiju-picnic-canvas/2PT2V3BM35HAMWGZX2HXOFHO",
    "framed-canvas": "https://miles2walk.square.site/product/kaiju-picnic-framed-canvas/7N7AHRT5FRIEMFR3GSE5KG35",
    "framed-poster": "https://miles2walk.square.site/product/kaiju-picnic-framed-poster/TBO3Z5VZOBHPCMHXN6QEYSAK",
    "metal": "https://miles2walk.square.site/product/kaiju-picnic-metal/2ANRA3D6PGV4P6GV72CTDWJA",
    "poster": "https://miles2walk.square.site/product/kaiju-picnic-poster/6PAAYDP4KV6Y2CEWE5XWMAKP"
   },
   "mockups": {
    "poster": "Images/mockups/kaiju-picnic-poster.webp",
    "framed-poster": "Images/mockups/kaiju-picnic-framed-poster.webp",
    "canvas": "Images/mockups/kaiju-picnic-canvas.webp",
    "framed-canvas": "Images/mockups/kaiju-picnic-framed-canvas.webp",
    "metal": "Images/mockups/kaiju-picnic-metal.webp"
   }
  },
  "croc-tank": {
   "title": "Croc Tank",
   "kind": "Urban Fantasy · Portrait",
   "thumb": "Images/thumbs/Croc_Tank.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/croc-tank-canvas/Z25DBUSPNI4VGIHKA6PKKWFR",
    "framed-canvas": "https://miles2walk.square.site/product/croc-tank-framed-canvas/S73OXXQOEFUDXQK237OZJINZ",
    "framed-poster": "https://miles2walk.square.site/product/croc-tank-framed-poster/5EHF6ZBWIRNOHUVE6GRGNK43",
    "metal": "https://miles2walk.square.site/product/croc-tank-metal/JUICWKD4WHVEDZ5K57UKIVXB",
    "poster": "https://miles2walk.square.site/product/croc-tank-poster/GXZYPUTCYTZVHI2DEOHH6USW"
   },
   "mockups": {
    "poster": "Images/mockups/croc-tank-poster.webp",
    "framed-poster": "Images/mockups/croc-tank-framed-poster.webp",
    "canvas": "Images/mockups/croc-tank-canvas.webp",
    "framed-canvas": "Images/mockups/croc-tank-framed-canvas.webp",
    "metal": "Images/mockups/croc-tank-metal.webp"
   }
  },
  "handmade-potions": {
   "title": "Handmade Potions",
   "kind": "Atmospheric · Landscape",
   "thumb": "Images/thumbs/Handmade_Potions.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/handmade-potions-canvas/3DXUKSZJMMYU6UOUUEY6IBF6",
    "framed-canvas": "https://miles2walk.square.site/product/handmade-potions-framed-canvas/J53VBYLFIRBGHN4QUSFA6NE7",
    "framed-poster": "https://miles2walk.square.site/product/handmade-potions-framed-poster/24W2XW5M4JMORDBUJPRC7EPJ",
    "metal": "https://miles2walk.square.site/product/handmade-potions-metal/KOENQOW4D7ADMTYHESIFM5WU",
    "poster": "https://miles2walk.square.site/product/handmade-potions-poster/AWW557FKEPYRTZXOKQLG2DUO"
   },
   "mockups": {
    "poster": "Images/mockups/handmade-potions-poster.webp",
    "framed-poster": "Images/mockups/handmade-potions-framed-poster.webp",
    "canvas": "Images/mockups/handmade-potions-canvas.webp",
    "framed-canvas": "Images/mockups/handmade-potions-framed-canvas.webp",
    "metal": "Images/mockups/handmade-potions-metal.webp"
   }
  },
  "fishing-for-trouble": {
   "title": "Fishing for Trouble",
   "kind": "Environment · Landscape",
   "thumb": "Images/thumbs/Fishing_For_Trouble_.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/fishing-for-trouble-canvas/U3EZHNQWUU24XHJWLLWGX5PL",
    "framed-canvas": "https://miles2walk.square.site/product/fishing-for-trouble-framed-canvas/INZIMYCBWQCDBB7FVDCOHYTD",
    "framed-poster": "https://miles2walk.square.site/product/fishing-for-trouble-framed-poster/M2QDHQK2L54ONWPFWABD3JMY",
    "metal": "https://miles2walk.square.site/product/fishing-for-trouble-metal/HU3XM62XTMJAF6VTHCNF7MEG",
    "poster": "https://miles2walk.square.site/product/fishing-for-trouble-poster/KKV34ZKIIC3NX4SHNQIRMSVO"
   },
   "mockups": {
    "poster": "Images/mockups/fishing-for-trouble-poster.webp",
    "framed-poster": "Images/mockups/fishing-for-trouble-framed-poster.webp",
    "canvas": "Images/mockups/fishing-for-trouble-canvas.webp",
    "framed-canvas": "Images/mockups/fishing-for-trouble-framed-canvas.webp",
    "metal": "Images/mockups/fishing-for-trouble-metal.webp"
   }
  },
  "commuters": {
   "title": "Commuters",
   "kind": "Urban Fantasy · Portrait",
   "thumb": "Images/thumbs/Commuters.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/commuters-canvas/WJJJOVPCIDPPWMLCMUKEH3AI",
    "framed-canvas": "https://miles2walk.square.site/product/commuters-framed-canvas/YL7PCYRVQJ5BGFOZQKFHAOJP",
    "framed-poster": "https://miles2walk.square.site/product/commuters-framed-poster/C5JTYG2FJ3O32ZLWJA2OZZQO",
    "metal": "https://miles2walk.square.site/product/commuters-metal/76G3FETDJBVF23HR36GV5YEF",
    "poster": "https://miles2walk.square.site/product/commuters-poster/VDYZG7GAP2NB3QE22KYG7Z56"
   },
   "mockups": {
    "poster": "Images/mockups/commuters-poster.webp",
    "framed-poster": "Images/mockups/commuters-framed-poster.webp",
    "canvas": "Images/mockups/commuters-canvas.webp",
    "framed-canvas": "Images/mockups/commuters-framed-canvas.webp",
    "metal": "Images/mockups/commuters-metal.webp"
   }
  },
  "chicken-ranch": {
   "title": "Chicken Ranch",
   "kind": "Texas Gothic · Portrait",
   "thumb": "Images/thumbs/Chicken_Ranch.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/chicken-ranch-canvas/RU65L4GML3IFDD7QHJBBPXAU",
    "framed-canvas": "https://miles2walk.square.site/product/chicken-ranch-framed-canvas/KHQCD3SYVFMANYGTK3N2BAMU",
    "framed-poster": "https://miles2walk.square.site/product/chicken-ranch-framed-poster/Z7B6TXKCPM22O7I7RQZQNGS3",
    "metal": "https://miles2walk.square.site/product/chicken-ranch-metal/FAH7XAPHBEE3XABNRRGOM7EA",
    "poster": "https://miles2walk.square.site/product/chicken-ranch-poster/6EBG7NEIHBRVRSN7X2ESSAFS"
   },
   "mockups": {
    "poster": "Images/mockups/chicken-ranch-poster.webp",
    "framed-poster": "Images/mockups/chicken-ranch-framed-poster.webp",
    "canvas": "Images/mockups/chicken-ranch-canvas.webp",
    "framed-canvas": "Images/mockups/chicken-ranch-framed-canvas.webp",
    "metal": "Images/mockups/chicken-ranch-metal.webp"
   }
  },
  "gladys": {
   "title": "Gladys",
   "kind": "Character · Portrait",
   "thumb": "Images/thumbs/Gladys.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/gladys-canvas/C3IZ55QKK6QE5UKGY7PQK5AV",
    "framed-canvas": "https://miles2walk.square.site/product/gladys-framed-canvas/FPA2MLBQP4IMROJEUSOCS5RG",
    "framed-poster": "https://miles2walk.square.site/product/gladys-framed-poster/B7T76GBCZHC2Y6G2EK4HLDXW",
    "metal": "https://miles2walk.square.site/product/gladys-metal/CNWMWZFS32Y5KMSSLNXI3X3X",
    "poster": "https://miles2walk.square.site/product/gladys-poster/TPE7KKW7N6X6PZEQICUW6WVL"
   },
   "mockups": {
    "poster": "Images/mockups/gladys-poster.webp",
    "framed-poster": "Images/mockups/gladys-framed-poster.webp",
    "canvas": "Images/mockups/gladys-canvas.webp",
    "framed-canvas": "Images/mockups/gladys-framed-canvas.webp",
    "metal": "Images/mockups/gladys-metal.webp"
   }
  },
  "grease-mill": {
   "title": "Grease Mill",
   "kind": "Environment · Portrait",
   "thumb": "Images/thumbs/Grease_Mill.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/grease-mill-canvas/MCA32NOLLQIEQVNIV4QQ7MJN",
    "framed-canvas": "https://miles2walk.square.site/product/grease-mill-framed-canvas/OSZPOVD3SQH4IHG5NOMH7KEL",
    "framed-poster": "https://miles2walk.square.site/product/grease-mill-framed-poster/YFFEAMBPR6ATKSI2QHNN3YZ4",
    "metal": "https://miles2walk.square.site/product/grease-mill-metal/QRPB2O5PD6TZIPGNXV3YIEPI",
    "poster": "https://miles2walk.square.site/product/grease-mill-poster/6QYWR3QY4BZOHTRA3DFTI3ZR"
   },
   "mockups": {
    "poster": "Images/mockups/grease-mill-poster.webp",
    "framed-poster": "Images/mockups/grease-mill-framed-poster.webp",
    "canvas": "Images/mockups/grease-mill-canvas.webp",
    "framed-canvas": "Images/mockups/grease-mill-framed-canvas.webp",
    "metal": "Images/mockups/grease-mill-metal.webp"
   }
  },
  "growth": {
   "title": "Growth",
   "kind": "Creature Design · Landscape",
   "thumb": "Images/thumbs/Growth.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/growth-canvas/SMRYMHAKN5NNFPZT3BW6JMV6",
    "framed-canvas": "https://miles2walk.square.site/product/growth-framed-canvas/ZND5RBQXJXUR3OVVAUXSPMUM",
    "framed-poster": "https://miles2walk.square.site/product/growth-framed-poster/LQ4PXDVYCCXUDT4L6PYDZQI5",
    "metal": "https://miles2walk.square.site/product/growth-metal/Z2JFT7EJUSVMFVRU64YKIIET",
    "poster": "https://miles2walk.square.site/product/growth-poster/XGLX6T4C65GRP7DJNSN2DCLG"
   },
   "mockups": {
    "poster": "Images/mockups/growth-poster.webp",
    "framed-poster": "Images/mockups/growth-framed-poster.webp",
    "canvas": "Images/mockups/growth-canvas.webp",
    "framed-canvas": "Images/mockups/growth-framed-canvas.webp",
    "metal": "Images/mockups/growth-metal.webp"
   }
  },
  "downtime": {
   "title": "Downtime",
   "kind": "Character · Portrait",
   "thumb": "Images/thumbs/Down_Time.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/downtime-canvas/Q6TPBOBAF52M4LLTIWHFKSQ5",
    "framed-canvas": "https://miles2walk.square.site/product/downtime-framed-canvas/PYTCJ4KVA22KBGWS2USCYCZX",
    "framed-poster": "https://miles2walk.square.site/product/downtime-framed-poster/PKDJIGBIYLCBA6MR2A2WOJUI",
    "metal": "https://miles2walk.square.site/product/downtime-metal/ZOCNAYT7SNG2FFSAZQDBOB2M",
    "poster": "https://miles2walk.square.site/product/downtime-poster/GKM2NR5YCMTIVDDBCX4KP6FL"
   },
   "mockups": {
    "poster": "Images/mockups/downtime-poster.webp",
    "framed-poster": "Images/mockups/downtime-framed-poster.webp",
    "canvas": "Images/mockups/downtime-canvas.webp",
    "framed-canvas": "Images/mockups/downtime-framed-canvas.webp",
    "metal": "Images/mockups/downtime-metal.webp"
   }
  },
  "seasonal": {
   "title": "Seasonal",
   "kind": "Atmospheric · Portrait",
   "thumb": "Images/thumbs/Seasonal.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/seasonal-canvas/6OBAQXVBWKVAIQVU5TNXAHYR",
    "framed-canvas": "https://miles2walk.square.site/product/seasonal-framed-canvas/F5AETSXUUJVDQZ47Q5GMF523",
    "framed-poster": "https://miles2walk.square.site/product/seasonal-framed-poster/GIGUG2I7MXN6X7ZJ6OSF35EB",
    "metal": "https://miles2walk.square.site/product/seasonal-metal/TAOMQP2T7FJKRUKEXZXJYNPP",
    "poster": "https://miles2walk.square.site/product/seasonal-poster/XMT23RJCSBJ3SDK3E7W447EA"
   },
   "mockups": {
    "poster": "Images/mockups/seasonal-poster.webp",
    "framed-poster": "Images/mockups/seasonal-framed-poster.webp",
    "canvas": "Images/mockups/seasonal-canvas.webp",
    "framed-canvas": "Images/mockups/seasonal-framed-canvas.webp",
    "metal": "Images/mockups/seasonal-metal.webp"
   }
  },
  "wildlife": {
   "title": "Wildlife",
   "kind": "Creature Design · Landscape",
   "thumb": "Images/thumbs/Wildlife.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/wildlife-canvas/CCFW4ELVXFEATEDMSUG7IQLR",
    "framed-canvas": "https://miles2walk.square.site/product/wildlife-framed-canvas/7EAPOF3OUNQO6BZXO3ZYUSCA",
    "framed-poster": "https://miles2walk.square.site/product/wildlife-framed-poster/H3CV7FYQA3NDJ56K23LGLY7M",
    "metal": "https://miles2walk.square.site/product/wildlife-metal/QIVR6GCZPC4GLRLUML6XTB27",
    "poster": "https://miles2walk.square.site/product/wildlife-poster/5LZM2WQ6JK7DZ6L6B3QRSARA"
   },
   "mockups": {
    "poster": "Images/mockups/wildlife-poster.webp",
    "framed-poster": "Images/mockups/wildlife-framed-poster.webp",
    "canvas": "Images/mockups/wildlife-canvas.webp",
    "framed-canvas": "Images/mockups/wildlife-framed-canvas.webp",
    "metal": "Images/mockups/wildlife-metal.webp"
   }
  },
  "naegelins-bakery": {
   "title": "Naegelin's Bakery",
   "kind": "Environment · Portrait",
   "thumb": "Images/thumbs/Naegelins_Bakery.webp",
   "products": {
    "canvas": "https://miles2walk.square.site/product/naeglin-s-bakery-canvas/SSJCWL2DLPOUBE44K2WWJ3V3",
    "framed-canvas": "https://miles2walk.square.site/product/naeglin-s-bakery-framed-canvas/UUJ5NHUBUX4IO4SHFOPOOF77",
    "framed-poster": "https://miles2walk.square.site/product/naeglin-s-bakery-framed-poster/B7SJ4RAVMGBX2QBLTECCPDXC",
    "metal": "https://miles2walk.square.site/product/naeglin-s-bakery-metal/4L3TE5KKOX3AUU5UP3D7IPWC",
    "poster": "https://miles2walk.square.site/product/naeglin-s-bakery-poster/JMRWXP5Y2SNHTDT4RYK35PVA"
   },
   "mockups": {
    "poster": "Images/mockups/naegelins-bakery-poster.webp",
    "framed-poster": "Images/mockups/naegelins-bakery-framed-poster.webp",
    "canvas": "Images/mockups/naegelins-bakery-canvas.webp",
    "framed-canvas": "Images/mockups/naegelins-bakery-framed-canvas.webp",
    "metal": "Images/mockups/naegelins-bakery-metal.webp"
   }
  }
 }
};
